steps:
# Copy resources
# - name: 'gcr.io/cloud-builders/gsutil'
#   args: ['cp', 'gs://bern2/resources_v1.1.b.tar.gz', '.']
  
# Docker Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/vertexai-375019/bern2/bern2:cloudbuild', '.']
  
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/vertexai-375019/bern2/bern2:cloudbuild']
  
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'bern2-cloudbuild', '--image', 'us-east1-docker.pkg.dev/vertexai-375019/bern2/bern2:cloudbuild', '--region', 'us-east1', '--platform', 'managed', '--allow-unauthenticated']
 
# Push the container image to Artifact Registry repo
images:
- 'us-east1-docker.pkg.dev/vertexai-375019/bern2/bern2:cloudbuild'